### ISSUE TITLE
SaveParameterInfo must go!

### ISSUE THREAD

**Issue by TonyBagnall** [uea-machine-learning/tsml#115]
So looking at my ancient interfaces to tidy/absorb or remove, we have
SaveParameterInfo: just a single abstract method that is surely better somewhere else, or just abandon for weka getOptions. 
Is there an easy way in netbeans to find all classes that implement an interface?

**Comment by James-Large** [comment]
Depends on what you want to ultimately use it for. In terms of strictly getting/setting parameters, get/setOptions is weirdly starting to get my vote, simply because it's already there. The times that **we** would use it I imagine are maybe reading parameters back from saved train estimates to test on in ClassifierResults files. Maybe we go further down the road of providing parameter setting files to e.g. cluster jobs, which are interpreted in setClassifier and the classifierName is altered to reflect them?

Otherwise, we typically use setClassifier with predefined parameters or are in some place in code where we can just use the setX methods for each parameter. 

Thing is, for ClassifierResults line to for example, it isn't only parameters that might want to go there (maybe CV results of each parameter search, weightings, any over info produced while training etc)

Back when the interface redesign was being planned, this was the change for saveParameterInfo

`
/**
 * This interface denotes that the classifier has information that it wants to save, which
 * would constitute the second line of a classifierResults file, aka get/setParas().
 * 
 * Anything can appear within this information, however it must fit onto a single line,
 * i.e. no newline characters. If some other process produces a string with newlines in it,
 * use str.replace("\n", delim), where delim is something unique enough to the classifier 
 * that the classifier itself could parse the information back in.
 * 
 * This line is only necessarily intended to be information for this same classifier when 
 * the results that this line is written to are read back in, and/or potentially 
 * a human reading the file. In the future, if e.g. usage of ParameterSet becomes
 * universally used, some structure may be enforced on this line, however for now 
 * it is up to the classifier what this line looks like.
 * 
 * Most commonly this line would used for the states of parameters after training, 
 * however may also be the results of a parameter search, a place to store any (very small) logs, etc.
 * 
 * @author James Large (james.large@uea.ac.uk)
 */
public interface SavableClassifierInformation {
    
    /**
     * @return a string containing no newline characters 
     */
    public String getClassifierInformation();
}
`

**Where one part of that could be the result of getOptions by default**, and then anything else the classifier might want to save afterwards

Though if we save options by default, may as we ll move up to the experimental level, but then that would bloat classiiferresults file size a lot

**Comment by TonyBagnall** [comment]
I agree its a bit weird using something called "getOptions" to getParameters(), but that is Weka speak and I think you have used setOptions for the generic tuner? So from the above, either 
a) go only with getOptions() or
b) refactor to SavableClassifierInformation, with a default method that returns getOptions()
does that sound reasonable? I think I would go for (b), not least because it is much easier than removing the interface SaveParameterInfo

**Comment by James-Large** [comment]
I guess it's get options since it isn't only parameters of the particular algorithm, but also meta/programmatic options like debug, seed etc. They're not parameters of the method, but options of the particular implementation within the codebase

Having a separate parameters interface which becomes a subset of options would be reasonable in concept then I guess, but could easily get annoying/fiddly to implement and maintain in classifiers

**Comment by TonyBagnall** [comment]
yeah think I will leave this for a bit, its not a biggie.
