### ISSUE TITLE
Tuning classifiers with TunedClassifier

### ISSUE THREAD

**Issue by TonyBagnall** [uea-machine-learning/tsml#127]
I'm doing a study of TSF and RISE in both sktime and, err, time-mine. I'm going to use James's TunedClassifier, which on first look seems excellent, documented, clear example etc, I may even use it correctly. My issue here is, should we have a new interface
interface Tuneable{
   ParameterSpace getDefaultParameterSpace()

}
and maybe more? Feels a little hacky manually setting it up in ClassifierLists

**Comment by James-Large** [comment]
Yeah I think so, makes most sense. Similar vein to discussion in other issue and the difference between options and specifically algorithmic parameters, maybe have both getDefaultParameterSpace() (getDefaultParameterTuningSpace() ?) and getDefaultParameterSet()

Think @goastler is potentially something with the whole parameters atm? This is stuff I wrote ages ago and haven't touched since, and was while we were only flirting with using get/setOptions. I've got no real investment on what happens with parameters/set/spaces

**Comment by TonyBagnall** [comment]
can defer all this, I'll run the relevant hive components with current set up. I'm leaning towards just using get/setOptions and abandoning out bespoke getParameters entirely, but wont do it for a bit

**Comment by TonyBagnall** [comment]
but we need to make sure all components implement setOptions so they can be tuned

**Comment by goastler** [comment]
just fyi EE runs with the set/ get options interface, it's extremely handy for tuning

**Comment by TonyBagnall** [comment]
does it implement saveParameterInfo? 
https://github.com/uea-machine-learning/tsml/issues/115

**Comment by TonyBagnall** [comment]
TunedClassifier works, can raise new issue if we ever get round to tuning HiveCote components ....
