### ISSUE TITLE
the result is different with http://timeseriesclassification.com/

### ISSUE THREAD

**Issue by shesheshebie2** [uea-machine-learning/tsml#190]
Hi
I run java/experiments/Experiments.java, I run UCR data, but the result is different with that in http://timeseriesclassification.com/. How to get the same result?

**Comment by James-Large** [comment]
Hi, this is likely a problem of the differences in data that came about with the 2018 ucr archive update. The results posted are from the original bake off on the archive as it was in 2015, while the datasets hosted are the up to date versions. 

In the 2018 update some of the existing datasets that had their numerical precision reduced due to problems with the original formatting were corrected, and so there are slight differences. E.g. Adiac instance 0 in the 2018 data: 

`1.5980065,1.5994389,1.5705294,1.5504735,1.5073709,1.4343414,1.3689859,1.3052935,1.2103053,1.1166533,1.0239758,0.92597745,0.82810675,0.73922239,0.64305122,0.5564315,0.4629485,0.36957542,0.27842598,0.18583002,0.095531978,0.010645835,-0.080855592,-0.16554948,-0.24349159,-0.33543018,-0.42610927,-0.49748567,-0.56685001,-0.64985597,-0.73224739,-0.77780027,-0.84298388,-0.91730416,-0.98797259,-1.0550113,-1.0967752,-1.1470648,-1.1984294,-1.2431884,-1.2816298,-1.3126376,-1.335745,-1.3511225,-1.37692,-1.3879348,-1.3768921,-1.3570987,-1.3295771,-1.2936916,-1.2576962,-1.2304194,-1.1742499,-1.1141994,-1.0720044,-1.0067549,-0.94892859,-0.87017066,-0.79017002,-0.72450665,-0.64283512,-0.59163379,-0.52139211,-0.43062968,-0.35084756,-0.26985588,-0.17363819,-0.089113314,-0.0039202835,0.08545283,0.17517592,0.26705534,0.36297072,0.45238072,0.54911159,0.64981693,0.74624359,0.84565871,0.94633349,1.0456812,1.1463071,1.2423602,1.3439936,1.4417984,1.5406627,1.6240945,1.6695854,1.6852007,1.6966604,1.6974616,1.687431,1.6385253,1.5737029,1.4785844,1.3769022,1.2765966,1.1770306,1.0776997,0.97920335,0.88053308,0.77792639,0.681645,0.5904323,0.49275089,0.40434261,0.30858913,0.2135155,0.12267702,0.037602884,-0.052601582,-0.13750988,-0.22040199,-0.31555828,-0.3946138,-0.44607596,-0.53343935,-0.60286039,-0.67340675,-0.7376065,-0.81902985,-0.88525804,-0.95008305,-1.002563,-1.0630029,-1.1251954,-1.1657686,-1.2042625,-1.2484515,-1.2737702,-1.2843798,-1.2733369,-1.2867387,-1.2918724,-1.2886474,-1.2777387,-1.2581449,-1.2313524,-1.1972685,-1.1563123,-1.1104562,-1.0845237,-1.0258311,-0.96255104,-0.89507051,-0.84781475,-0.77253707,-0.69457342,-0.63199846,-0.55121949,-0.48458675,-0.40867694,-0.32442403,-0.24745378,-0.16365095,-0.076912929,0.0088012471,0.09727377,0.1858962,0.28400462,0.38120517,0.46302539,0.55693306,0.65096988,0.73820038,0.83474166,0.92993859,1.0248605,1.1209061,1.2171752,1.3125298,1.4029198,1.4810428,1.5210116,1.5641545,1.5708545,1.5928905,22`

and adiac instance 0 in the 2015 data:

`1.598,1.5994,1.5705,1.5505,1.5074,1.4343,1.369,1.3053,1.2103,1.1167,1.024,0.92598,0.82811,0.73922,0.64305,0.55643,0.46295,0.36958,0.27843,0.18583,0.095532,0.010646,-0.080856,-0.16555,-0.24349,-0.33543,-0.42611,-0.49749,-0.56685,-0.64986,-0.73225,-0.7778,-0.84298,-0.9173,-0.98797,-1.055,-1.0968,-1.1471,-1.1984,-1.2432,-1.2816,-1.3126,-1.3357,-1.3511,-1.3769,-1.3879,-1.3769,-1.3571,-1.3296,-1.2937,-1.2577,-1.2304,-1.1742,-1.1142,-1.072,-1.0068,-0.94893,-0.87017,-0.79017,-0.72451,-0.64284,-0.59163,-0.52139,-0.43063,-0.35085,-0.26986,-0.17364,-0.089113,-0.00392,0.085453,0.17518,0.26706,0.36297,0.45238,0.54911,0.64982,0.74624,0.84566,0.94633,1.0457,1.1463,1.2424,1.344,1.4418,1.5407,1.6241,1.6696,1.6852,1.6967,1.6975,1.6874,1.6385,1.5737,1.4786,1.3769,1.2766,1.177,1.0777,0.9792,0.88053,0.77793,0.68164,0.59043,0.49275,0.40434,0.30859,0.21352,0.12268,0.037603,-0.052602,-0.13751,-0.2204,-0.31556,-0.39461,-0.44608,-0.53344,-0.60286,-0.67341,-0.73761,-0.81903,-0.88526,-0.95008,-1.0026,-1.063,-1.1252,-1.1658,-1.2043,-1.2485,-1.2738,-1.2844,-1.2733,-1.2867,-1.2919,-1.2886,-1.2777,-1.2581,-1.2314,-1.1973,-1.1563,-1.1105,-1.0845,-1.0258,-0.96255,-0.89507,-0.84781,-0.77254,-0.69457,-0.632,-0.55122,-0.48459,-0.40868,-0.32442,-0.24745,-0.16365,-0.076913,0.008801,0.097274,0.1859,0.284,0.38121,0.46303,0.55693,0.65097,0.7382,0.83474,0.92994,1.0249,1.1209,1.2172,1.3125,1.4029,1.481,1.521,1.5642,1.5709,1.5929,22`

For a few classifiers I quickly tested in response to this issue, I could exactly recreated results on the 2015 data, but there are insignificant on average differences on the 2018 data. 

Data differences, as well as minor differences to classifier that creep in over 4 or 5 years due to refactors and structural changes mean that not all the bakeoff results can be guaranteed to be reproducible with current code. Various classifiers will behave differently given higher precision, but on average over all problems (I don't know how many were updated, certainly less than 10 as far as I know) there shouldn't be any significant differences

However, bake off 2 with updated and new classifiers and datasets might come at some point :)

**Comment by shesheshebie2** [comment]
Thanks for your answer， I just want to know Whether the configuration is wrong.

**Comment by TonyBagnall** [comment]
hi, let us know if you are still having problems recreating the results
